### ISSUE TITLE
How to implement IPC provider ?

### ISSUE THREAD

**Issue by billyadelphia** [distributed-ledger-technology/web3#36]
Hi, Is it possible to use IPC provider on the current state of deno ?
I'm using deno 1.18.2

I have tried to implement like this
```js
import net from "https://deno.land/std@0.125.0/node/net.ts";
import Web3 from "https://deno.land/x/web3/mod.ts";

const provider = new Web3.providers.IpcProvider(
      "/root/geth_data/geth.ipc",
      net
    );
const web3 = new Web3(provider);
```

and got these error
```
error: Uncaught (in promise) Error: Not implemented
  throw new Error(message);
        ^
    at notImplemented (https://deno.land/std@0.125.0/node/_utils.ts:23:9)
    at Pipe.connect (https://deno.land/std@0.125.0/node/internal_binding/pipe_wrap.ts:93:5)
    at _internalConnect (https://deno.land/std@0.125.0/node/net.ts:470:36)
    at defaultTriggerAsyncIdScope (https://deno.land/std@0.125.0/node/_async_hooks.ts:57:18)
    at Socket.connect (https://deno.land/std@0.125.0/node/net.ts:926:7)
    at Object.connect (https://deno.land/std@0.125.0/node/net.ts:1580:17)
    at new IpcProvider (https://deno.land/x/web3@v0.9.2/packages/web3-providers-ipc/src/index.js:35:25)
```

The IPC implementation is working fine on node.js

**Comment by michael-spengler** [comment]
https://docs.ethers.io/v5/api/providers/other/#Web3Provider
